export const AUTUMN_LEAVES = {
  name: 'autumn leaves',
  sheetContents: [
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: 'W9fC_PZ3oOxbx_MoLPTIp',
      overlayRoot: 'A',
      overlayMode: 'chord',
      overlayChordType: 'minor seventh',
      overlayScaleType: 'major',
      notes:
        "This practice sheet outlines the chord changes in the jazz standard Autumn Leaves, overlaying each chord over the key in which the song is in.\n\nOf course, you can play other scales over these chords, I just don't know enough music theory so I've stuck with the safe choice.",
    },
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: 'ZfcsDmDdNE3lOb7_IQFIR',
      overlayRoot: 'D',
      overlayMode: 'chord',
      overlayChordType: 'dominant seventh',
      overlayScaleType: 'major',
      notes: 'I think you can play D mixolydian here. ',
    },
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: '89MZ4Eq8hBb1xCbx3HLDL',
      overlayRoot: 'G',
      overlayMode: 'chord',
      overlayChordType: 'major seventh',
      overlayScaleType: 'major',
      notes: null,
    },
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: '9TkHgGGvZa8uJykSImkrK',
      overlayRoot: 'C',
      overlayMode: 'chord',
      overlayChordType: 'major seventh',
      overlayScaleType: 'major',
      notes: null,
    },
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: '9thKfMTNz0M63uVN2iVGG',
      overlayRoot: 'Gb',
      overlayMode: 'chord',
      overlayChordType: 'diminished',
      overlayScaleType: 'major',
      notes: null,
    },
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: 'g_ECmEW0KwWqYaeB5jYAx',
      overlayRoot: 'B',
      overlayMode: 'chord',
      overlayChordType: 'dominant seventh',
      overlayScaleType: 'major',
      notes: null,
    },
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: 'tS1lOyoz8jWpiZ3j4pktO',
      overlayRoot: 'E',
      overlayMode: 'chord',
      overlayChordType: 'minor seventh',
      overlayScaleType: 'major',
      notes: null,
    },
  ],
  creation_date: '2023-05-11T00:24:06.893Z',
}

export const BASIC_SCALE_PRACTICE = {
  name: 'basic scale practice',
  id: 'gfpqfYNcwbgY0FUxzj8fM',
  sheetContents: [
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'A',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor pentatonic',
      id: '4_uN4gEGhFDOWVajQRUyS',
      overlayRoot: 'G',
      overlayMode: null,
      overlayChordType: 'major',
      overlayScaleType: 'major',
      notes:
        "If you're really serious about music, you should practice every key, but A and E serve as pretty good starting points.",
    },
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor pentatonic',
      id: 'rQojy2yductQjVPggPuyA',
      overlayRoot: 'G',
      overlayMode: null,
      overlayChordType: 'major',
      overlayScaleType: 'major',
      notes: null,
    },
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'A',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: 'gq5VoYSD9RVJvemedlK7M',
      overlayRoot: 'G',
      overlayMode: null,
      overlayChordType: 'major',
      overlayScaleType: 'major',
      notes: null,
    },
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: 'Q_7KjTm49RuBAkpqMCGjx',
      overlayRoot: 'G',
      overlayMode: null,
      overlayChordType: 'major',
      overlayScaleType: 'major',
      notes: null,
    },
  ],
  creation_date: '2023-05-11T00:07:31.218Z',
}

export const COMPARING_SCALES = {
  name: 'comparing modes and underlying scales',
  id: 'ilDtCdWODe0JFMZJMPUqS',
  sheetContents: [
    {
      stringSpacing: 20,
      fretSpacing: 50,
      frets: 15,
      tuning: ['E4', 'B3', 'G3', 'D3', 'A2', 'E2'],
      root: 'E',
      mode: 'scale',
      chordType: 'major',
      scaleType: 'minor',
      id: 'fieQJ2dywTYQRpQJHOie3',
      overlayRoot: 'E',
      overlayMode: 'scale',
      overlayChordType: 'major',
      overlayScaleType: 'dorian',
      notes:
        'As you can see, the main difference between E dorian and E minor is the Db.\n\nE dorian has a sharp 6 compared to E minor\n\nNote to self: should really support setting #/b settings on individual fretboards - C# is better notation than Db here.\n',
    },
  ],
  creation_date: '2023-05-11T00:36:54.107Z',
}
